# Generated by Django 5.1.6 on 2025-02-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(verbose_name="Дата выхода на рынок"),
        ),
    ]
