# Generated by Django 5.1.6 on 2025-02-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="networknode",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
